support kernel 5.12+
jserv/simplefs pull request #18
Opened 2022-03-05 21:56 UTC by dimorinny

Signature changes, that allow using simplefs with 5.12+ kernel.

2022-03-06 03:25 UTC, jserv requested changes
Use conditional build to allow older kernel versions.

2022-03-07 00:18 UTC, dimorinny commented
Done

2022-03-07 01:48 UTC, jserv commented on simplefs.h
> +#define user_namespace_required() LINUX_VERSION_CODE >= KERNEL_VERSION(5,12,0)
Use capitalized macro. That is, `USER_NS_REQUIRED`.

2022-03-07 17:13 UTC, merged

2022-03-07 17:13 UTC, jserv commented
Thank @dimorinny for contributing!