binary search implementation for `simplefs_ext_search`
jserv/simplefs pull request #42
Opened 2024-04-22 16:32 UTC by baekrang256

2024-04-22 21:28 UTC, jserv requested changes
Run `clang-format -i` for consistent style.

2024-04-23 05:16 UTC, jserv commented on extent.c
> + * Implemented binary search for efficiency
Rephrase as following:
> Binary search is used for efficiency.

2024-04-23 05:17 UTC, jserv commented on extent.c
> +        } else if (iblock < block) {
Remove `else`. That is,
```c
        if (iblock >= block && iblock < block + len) {
            /* found before search finished */
            return mid;
        }
        if (iblock < block)
            end = mid;
        else
            start = mid + 1;
```

2024-04-23 05:18 UTC, jserv commented on extent.c
> +    if (iblock >= end_block && iblock < end_len) {
Ditto. Rewrite as following:
```c
    if (iblock >= end_block && iblock < end_len)
        return end;
    return boundary;
```

2024-04-23 05:19 UTC, jserv requested changes
Use `git rebase -i` to squash the commits and read the article [How to Write a Git Commit Message](https://cbea.ms/git-commit/) to refine the commit message.

2024-04-23 14:48 UTC, jserv commented
@baekrang256, can you figure out the reason why GitHub Actions can not complete the tests?

2024-04-23 20:12 UTC, RoyWFHuang commented
These are some bugs in this function. I dump the kernel message and it shows:
`[  333.089632] BUG: unable to handle page fault for address: ffff94e6dcb34ff8`
`[  333.099146] RIP: 0010:simplefs_ext_search.cold+0x46/0xa5 [simplefs]`

By the information 0x46, we can find 
`  46:	41 8b 78 04          	mov    0x4(%r8),%edi`
`        uint32_t len = index->extents[mid].ee_len;`
it seems that the "mid" is out of range, so you may need to check when the "end" is 0 and  assign to "boundary", which will make "end" reach to unsinged max 

Another thing, you should also consider when the "end" is MAX_EXTENTS and ee_start != 0, this will also cause the same error.

2024-04-24 03:32 UTC, baekrang256 commented
There were indeed some corner cases mentioned by @RoyWFHuang . Thanks for the review.

I've fixed the code and tried the CI test in my local environment, checked the output comes out as expected according to other CI test outputs from other pr. I think we can try out the github action workflow again. 

One additional question : should I rebase the branch again before the merge?

2024-04-24 03:44 UTC, jserv commented
> One additional question : should I rebase the branch again before the merge?

Yes, please go ahead.

2024-04-24 04:44 UTC, baekrang256 commented
Finished rebasing.

2024-04-24 05:43 UTC, merged

2024-04-24 05:43 UTC, jserv commented
Thank @baekrang256 for contributing!