Fix errors raised by missing-prototypes
jserv/simplefs pull request #46
Opened 2024-05-03 08:41 UTC by HotMercury

In the current attempt to run simplefs on the Linux kernel v6.8 environment, encountering the error "no previous prototype for `simplefs_mount`" indicates a need for additional function declarations. 
```
error: no previous prototype for ‘simplefs_mount’
error: no previous prototype for ‘simplefs_kill_sb’ 
```
The reason why it worked in previous versions is that the changes related to `-Wmissing-declarations` and `-Wmissing-prototypes` were introduced in 6.8-rc1 in [commit 0fcb708](https://github.com/torvalds/linux/commit/0fcb70851fbfea1776ae62f67c503fef8f0292b9) .

2024-05-03 10:27 UTC, jserv requested changes
Improve git commit message!

2024-05-03 11:12 UTC, HotMercury commented
Can I fix it like this?
The original program triggered compile-time errors due to missing function prototype declarations for 'simplefs_mount' and 'simplefs_kill_sb'. This commit addresses the issue by adding the necessary function prototype declarations, resolving the compilation errors.

2024-05-03 13:27 UTC, jserv commented
> Can I fix it like this? The original program triggered compile-time errors due to missing function prototype declarations for 'simplefs_mount' and 'simplefs_kill_sb'. This commit addresses the issue by adding the necessary function prototype declarations, resolving the compilation errors.

No, you must mention the considerations of upstream Linux changes that enforce function prototype checks, along with their impact on this project. Additionally, it is important to be aware of how to avoid missing function prototypes.

2024-05-05 10:49 UTC, jserv requested changes
Mention upstream SHA-1 hash which enforce missing-prototypes checks.

2024-05-05 17:50 UTC, jserv requested changes
Make the git commit message grammatical accuracy.

2024-05-06 01:15 UTC, merged

2024-05-06 01:15 UTC, jserv commented
Thank @HotMercury for contributing!