External journal device initial and have some thoughts with writing metadata with journal
jserv/simplefs pull request #59
Opened 2024-06-20 03:16 UTC by jason50123

This pull request currently adds the parse_option in fill super to mount the external journal device to simplefs. It also writes the currently accessible extent metadata to the journal during write operations. The image below demonstrates that it is already possible to mount the external journal device in the v6.8 environment.

- Implement external journal device initialization
- Add journal to write function

![螢幕快照 2024-06-20 10-17-03](https://github.com/sysprog21/simplefs/assets/57582802/2fbd3355-9a13-486b-a6d7-eed80fe1e8b4)

2024-06-20 03:20 UTC, jserv commented
Avoid uploading screenshots that contain only text. Instead, use Markdown formatting to present command lists, source code, and any text-based content. This approach is more accessible for individuals with visual impairments.

2024-06-20 03:21 UTC, jserv commented on file.c
> +    // handle journal start here
Always use C-style comments.

2024-06-20 03:22 UTC, jserv commented on super.c
> +
Remove one blank line.

2024-06-20 03:22 UTC, jserv commented on super.c
> +     *Fix me: This number is calculated by dividing the external device capacity
Specify "FIXME" instead of "Fix me."

2024-06-20 03:22 UTC, jserv commented on super.c
> +     *(8MB) by the external device block size (4096). Currently, I don't know
Improve your English writing.

2024-06-20 03:24 UTC, jserv commented on super.c
> +    while ((p = strsep(&options, ",")) != NULL) {
Simply rewrite as `while ((p = strsep(&options, ","))) {`

2024-06-20 03:25 UTC, jserv requested changes
Append the test suite to reflect journaling support.

2024-06-20 03:26 UTC, jserv commented
Drop unnecessary `pr_info` statements.

2024-06-20 03:28 UTC, jserv commented
Fix compatibility with Linux v6.5:
```
simplefs/super.c: In function ‘simplefs_get_journal_blkdev’:
simplefs/super.c:221:19: error: implicit declaration of function ‘bdev_open_by_dev’; did you mean ‘blkdev_get_by_dev’? [-Werror=implicit-function-declaration]
  221 |     bdev_handle = bdev_open_by_dev(
      |                   ^~~~~~~~~~~~~~~~
      |                   blkdev_get_by_dev
simplefs/super.c:222:48: error: ‘BLK_OPEN_RESTRICT_WRITES’ undeclared (first use in this function)
  222 |         jdev, BLK_OPEN_READ | BLK_OPEN_WRITE | BLK_OPEN_RESTRICT_WRITES, sb,
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
```

2024-06-21 21:31 UTC, jason50123 commented
The latest commit has addressed the mentioned issues. 
Evidence of the journal functioning correctly will be provided later.

2024-06-22 01:22 UTC, jserv requested changes
Use `git rebase -i` to rework the commits.

2024-06-22 01:26 UTC, jserv commented on super.c
> +
Remove this blank line.

2024-06-22 01:28 UTC, jserv requested changes
Ensure that journal device can be mounted for Linux kernels prior to v6.5. At least, tweak for version 6.1, 5.15, and 5.10.
See https://kernel.org/ for LTS.

2024-06-22 04:51 UTC, jason50123 commented
@jserv Could you please clarify if you would like me to rebase all the commits into a single commit, or if there is a specific way you prefer me to rework them? Thank you!

2024-06-22 06:07 UTC, jserv commented
> @jserv Could you please clarify if you would like me to rebase all the commits into a single commit, or if there is a specific way you prefer me to rework them? Thank you!

There should be only one commit rebasing the latest `master` branch for reviewing. See https://git-scm.com/docs/git-rebase

2024-06-22 21:39 UTC, closed without merging