Fix Symbolic link remove problem
jserv/simplefs pull request #64
Opened 2024-08-18 08:48 UTC by RoyWFHuang

When we create symbolic link, in simplefs_new_inode function, the symbolic
does not use ei_block to record the using block. But in simplefs_unlink function we use the ei_block to clean the bitmap, this makes the unlink will clean the "0" bit in bitmap.

Close #58

2024-08-19 10:23 UTC, HotMercury commented
This PR indeed fixes the symbolic bug. 
Could you please provide a test case in the test file?

2024-08-19 10:56 UTC, RoyWFHuang commented
Updated.

2024-08-19 12:14 UTC, jserv requested changes
Consolidate the test suite to reflect the proposed changes as @HotMercury requested.

2024-08-20 13:53 UTC, merged

2024-08-20 13:53 UTC, jserv commented
Thank @RoyWFHuang for contributing!